# version: '3'

services :
  source_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: source_db
    ports:
      - "5433:5432"
    networks:
      - elt_network
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  destination_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: destination_db
    ports:
      - "5434:5432"
    networks:
      - elt_network
  elt_script:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
    volumes:
      - shared:/shared
    
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    entrypoint: ["sh", "/wait_for_etl.sh"]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
      - shared:/shared
      - ./wait_for_etl.sh:/wait_for_etl.sh
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: custom_postgres
      DBT_TARGET: dev
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5435:5432"
    networks:
      - elt_network
  
networks:
  elt_network:
    driver: bridge

volumes:
  shared: